title: Yashwanth Gopal
logo: "/profile.png?raw=true"
description: > 
  Data Engineer
  <br><br>
  <a href="mailto:yashwanth.0568@gmail.com">yashwanth.0568@gmail.com</a>
  <br>
  <a href="https://www.linkedin.com/in/g-yashwanth/">LinkedIn Profile</a>
theme: jekyll-theme-minimal
